# Generated by Django 5.1.6 on 2025-03-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_remove_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Profil Resmi'),
        ),
    ]
