# Generated by Django 5.1.6 on 2025-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile Card Section'},
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='İletişim Bilgileri'),
        ),
    ]
